---
title: "Assignment 4"
output: word_document
---
#Importing Libraries

```{r}
library(randomForest)
library(caret)
library(ggplot2)
library(mlbench)
```

#Importing Data

```{r}
data(BreastCancer) 
head(BreastCancer)
levels(BreastCancer$Class)
```

#Finding missing values and removing them

```{r}
sum(is.na(BreastCancer))
BreastCancer <- na.omit(BreastCancer)[,c(2:11)]
```

#Splitting the data into 70% training and 30% testing.

```{r}
set.seed(15)
intrain <- createDataPartition(y = BreastCancer$Class, p = 0.7, list = FALSE)
training <- BreastCancer[intrain,]
testing <- BreastCancer[-intrain,]
```

#SVM model without grid search.

```{r}
set.seed(15)
svm.model <- train(Class~., data = training, method = 'svmLinear', scale = FALSE)
svm.model
```


#Confusion Matrix:

```{r}
results <- predict(svm.model, testing, type = "raw")
table(results, testing$Class)
```


#Examining the following values for the mtry variable: 1, 2.5, 6.25

```{r}
set.seed(15)
Grid_Serach <- expand.grid(.C=c(1,2.5,6.25))
svm.model2 <- train(Class~., data = training, method='svmLinear', tuneGrid = Grid_Serach, scale = FALSE)
svm.model2
```


#Confusion Matrix:

```{r}
pred_class <- predict(svm.model2, testing, type="raw")
head(pred_class)
table(pred_class, testing$Class)
```

#We have an accuracy of 95.1% for C = 1.
